### ISSUE TITLE
/usr/include/nativeextractor/nativeextractor

### ISSUE THREAD

**Issue by i032** [SpongeData-cz/nativeextractor#2]
After installation (make install) headers copies not correctly.

Current path: `/usr/include/nativeextractor/nativeextractor`
Expected path: `/usr/include/nativeextractor`

**Comment by mafiosso** [comment]
It is due to `nativeextractor.pc` - if you use pkg-config then you do `#include <nativeextractor/common.h>`, if you do not you have to write `#include <nativeextractor/nativeextractor/common.h>` which is little bit confusing - I agree.

**Comment by michaelspongedata** [comment]
Fixed in commit 47c7310.
